version: '3.7'

services:
    db:
        image: postgres:12
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - 5439:5432

    auth_service:
        build: .
        volumes:
            - .:/usr/auth_service
        ports:
            - 3000:3000
        depends_on:
            - db
